package com.zhy20.teleprompter.data.importer

import com.zhy20.teleprompter.core.model.ScriptBlock
import com.zhy20.teleprompter.core.model.ScriptSpan
import java.io.ByteArrayInputStream
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Unit tests for [DocxScriptImporter] driven by the fixed DOCX fixture under
 * src/test/resources/fixtures/. The fixtures are tiny, hand-checked files generated by Microsoft
 * Word (no personal data, no external links) and committed so tests are reproducible offline.
 */
class DocxScriptImporterTest {

    private fun fixtureBytes(name: String): ByteArray =
        checkNotNull(javaClass.classLoader.getResourceAsStream("fixtures/$name")) { "missing fixture $name" }
            .use { it.readBytes() }

    private suspend fun import(name: String, mime: String? = DocxScriptImporter.MimeTypeWordOpenXml, size: Long? = null): ImportedScript {
        val bytes = fixtureBytes(name)
        return DocxScriptImporter().import(
            ImportFileMetadata(name, mime, size ?: bytes.size.toLong()),
        ) { ByteArrayInputStream(bytes) }
    }

    private fun textOf(doc: com.zhy20.teleprompter.core.model.ScriptDocument): String = doc.plainText()

    private fun paragraphsOf(doc: com.zhy20.teleprompter.core.model.ScriptDocument): List<ScriptBlock.Paragraph> =
        doc.blocks.map { it as ScriptBlock.Paragraph }

    @Test
    fun supports_acceptsDocxExtensionAndMime() {
        val importer = DocxScriptImporter()
        assertTrue(importer.supports(ImportFileMetadata("a.docx", null, null)))
        assertTrue(importer.supports(ImportFileMetadata("a", DocxScriptImporter.MimeTypeWordOpenXml, null)))
        assertFalse(importer.supports(ImportFileMetadata("a.doc", null, null)))
        assertFalse(importer.supports(ImportFileMetadata("a.txt", "text/plain", null)))
    }

    @Test
    fun realSample_extractsAllParagraphsInOrder() = runBlocking {
        val result = import("real_sample.docx")
        assertEquals("real_sample", result.suggestedTitle)
        val paragraphs = paragraphsOf(result.document)
        assertTrue(paragraphs.size >= 3)
        assertEquals("第一段：这是一份用于测试的样本。", paragraphs[0].spans.joinToString("") { it.text })
        assertEquals("Second paragraph with English text.", paragraphs[1].spans.joinToString("") { it.text })
        assertEquals("第三段结尾。", paragraphs[2].spans.joinToString("") { it.text })
    }

    @Test
    fun titleDropsDocxExtension() = runBlocking {
        val result = import("real_sample.docx")
        assertEquals("real_sample", result.suggestedTitle)
    }

    @Test
    fun emptyDocument_fails() = runBlocking {
        val xml = """
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body></w:body></w:document>
        """.trimIndent()
        val bytes = buildDocx(mapOf("word/document.xml" to xml.toByteArray()))
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("empty.docx", DocxScriptImporter.MimeTypeWordOpenXml, bytes.size.toLong()),
            ) { ByteArrayInputStream(bytes) }
            fail("Expected empty exception")
        } catch (e: ScriptImportException) {
            assertEquals(ScriptImportError.Empty, e.error)
        }
    }

    @Test
    fun corruptZip_fails() = runBlocking {
        val bytes = byteArrayOf(0x50, 0x4B, 0x03, 0x04, 0x01, 0x02, 0x03) // truncated zip header
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("bad.docx", DocxScriptImporter.MimeTypeWordOpenXml, bytes.size.toLong()),
            ) { ByteArrayInputStream(bytes) }
            fail("Expected corrupt exception")
        } catch (e: ScriptImportException) {
            assertEquals(ScriptImportError.Corrupt, e.error)
        }
    }

    @Test
    fun missingDocumentXml_fails() = runBlocking {
        val bytes = buildDocx(mapOf("word/settings.xml" to "<x/>".toByteArray()))
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("no_doc.xml", DocxScriptImporter.MimeTypeWordOpenXml, bytes.size.toLong()),
            ) { ByteArrayInputStream(bytes) }
            fail("Expected corrupt exception")
        } catch (e: ScriptImportException) {
            assertEquals(ScriptImportError.Corrupt, e.error)
        }
    }

    @Test
    fun oversizedByMetadata_fails() = runBlocking {
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("big.docx", DocxScriptImporter.MimeTypeWordOpenXml, WordImportLimits.MAX_SOURCE_FILE_BYTES + 1),
            ) { ByteArrayInputStream(ByteArray(0)) }
            fail("Expected too-large exception")
        } catch (e: ScriptImportException) {
            assertEquals(ScriptImportError.TooLarge, e.error)
        }
    }

    @Test
    fun zipBomb_fails() = runBlocking {
        // A true zip bomb: a highly compressible payload that exceeds the entry size budget.
        val bombXml = ("<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body>"
            + "A".repeat(WordImportLimits.MAX_ENTRY_BYTES.toInt() + 1024)
            + "</w:body></w:document>")
        val bytes = buildDocx(mapOf("word/document.xml" to bombXml.toByteArray()))
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("bomb.docx", DocxScriptImporter.MimeTypeWordOpenXml, bytes.size.toLong()),
            ) { ByteArrayInputStream(bytes) }
            fail("Expected too-complex exception")
        } catch (e: ScriptImportException) {
            assertTrue(
                "expected TooComplex or Corrupt, got ${e.error}",
                e.error == ScriptImportError.TooComplex || e.error == ScriptImportError.Corrupt,
            )
        }
    }

    @Test
    fun tooManyEntries_fails() = runBlocking {
        val bytes = buildDocx(emptyMap(), extraEntries = WordImportLimits.MAX_ZIP_ENTRIES + 10)
        try {
            DocxScriptImporter().import(
                ImportFileMetadata("many.docx", DocxScriptImporter.MimeTypeWordOpenXml, bytes.size.toLong()),
            ) { ByteArrayInputStream(bytes) }
            fail("Expected too-complex exception")
        } catch (e: ScriptImportException) {
            assertEquals(ScriptImportError.TooComplex, e.error)
        }
    }

    private fun buildDocx(
        entries: Map<String, ByteArray>,
        extraEntries: Int = 0,
    ): ByteArray {
        val bos = java.io.ByteArrayOutputStream()
        ZipOutputStream(bos).use { zip ->
            zip.putNextEntry(ZipEntry("[Content_Types].xml"))
            zip.write("<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"/>".toByteArray())
            zip.closeEntry()
            entries.forEach { (name, data) ->
                zip.putNextEntry(ZipEntry(name))
                zip.write(data)
                zip.closeEntry()
            }
            repeat(extraEntries) {
                zip.putNextEntry(ZipEntry("extra_$it.bin"))
                zip.write(0)
                zip.closeEntry()
            }
        }
        return bos.toByteArray()
    }
}
